version: '3'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/var/lib/redisinsight/db

volumes:
  database:
  redisinsight:
